#!/usr/bin/env ruby
require_relative "./0-helpers"

h1 "Modelines"

h2 "Emacs"
EMACS = load_regexp("../modeline-emacs.regexp")
match EMACS, "-*- ruby -*-", "ruby"
match EMACS, "-*- foo:bar; mode: ruby; -*-", "ruby"
match EMACS, "-*-mode:ruby-*-", "ruby"
match EMACS, "-*- mode: ruby -*-", "ruby"
match EMACS, "-*- mode  : ruby -*-", "ruby"
match EMACS, "-*- ruby-*-", "ruby"
match EMACS, "-*-c++-*-", "c++"
match EMACS, "-*- c++ -*-", "c++"
match EMACS, "-*- mode:C++ -*-", "C++"
match EMACS, "-*- font:bar;mode:c++ -*-", "c++"
match EMACS, "-*-foo:bar;mode:c++;bar:foo-*-", "c++"
match EMACS, "-*- foo : bar ; mode : c++ ; bar : foo -*-", "c++"
match EMACS, "-*- mode : c++ ; bar : foo -*-", "c++"
match EMACS, "-*- font:x;foo : bar ; mode : C++ ; bar : foo ; foooooo:baaaaar;fo:ba-*-", "C++"
match EMACS, "-*-foo:bar;mode:c++;bar:foo;tyrell:corp-*-", "c++"
match EMACS, "-*- foo-bar mode: c++ -*-", "c++"
match EMACS, "-*--------- foo:bar mode: c++ -*-", "c++"
match EMACS, "/* -*- mode: c++ -------*- */", "c++"
match EMACS, "; -*- MoDe: PhP;-*-", "PhP"
match EMACS, "; -*-mode:Smalltalk-*-", "Smalltalk"
match EMACS, "// -*- fundamental -*-", "fundamental"
miss  EMACS, "-*- foo:bar bar:baz;"
miss  EMACS, "-*- ruby --*-"
miss  EMACS, "-*- ruby--*-"

h2 "Vim"
VIM = load_regexp("../modeline-vim.regexp")
match VIM, "# vim: noexpandtab: ft=conf", "conf"
match VIM, "# vim:noexpandtab titlestring=hi|there\\\\ ft=js ts=4", "js"
match VIM, "vim: noai :  ft=sh:noexpandtab", "sh"
match VIM, "vim: noai ft=js noexpandtab", "js"
match VIM, "vim: ft   =ruby", "ruby"
match VIM, "/* vim: set filetype=a65: */", "a65"
match VIM, "/* vim: set ts=8 sw=4 filetype=bash tw=0: */", "bash"
match VIM, "/* vim: set ft=ruby ts=8 sw=4 tw=0: */", "ruby"
match VIM, "# vim: filetype=ruby", "ruby"
match VIM, "# vim: ft=ruby", "ruby"
match VIM, "# vim: syntax=Ruby", "Ruby"
match VIM, "# vim: se syntax=ruby:", "ruby"
match VIM, "# vim: set syntax=ruby:", "ruby"
match VIM, "# ex: syntax=ruby", "ruby"
match VIM, " ex: noexpandtab: ft=ruby", "ruby"
match VIM, "# vim600: ft=ruby", "ruby"
match VIM, "vim<520: ft=ruby", "ruby"
match VIM, "/* vim: set ft=cpp: */", "cpp"
miss  VIM, "# vim:noexpandtab titlestring=hi\|there\\\ ft=perl ts=4"
miss  VIM, "/* vim: set filEtype=pRoloG: */"
miss  VIM, "ex: noexpandtab: ft=ruby"
miss  VIM, "vim: titlestring=\\ ft=perl"
miss  VIM, "vim: ft= "
